version: '3'

services:
  product-service:
    build: ./service
    platform: linux/amd64
    #command: sh -c "sleep 10s"
    volumes:
      - ./service:/usr/src/app
    ports:
      - 5001:80


  website:
    image: php:apache
    #command: sh -c "sleep 15s"
    volumes:
      - ./website:/var/www/html
    ports:
      - 8081:80
    depends_on:
      - product-service

  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
